// == AUTENTICAÇÃO ==

POST http://localhost:3000/api/authentication/registro // REGISTRAR USUÁRIO
{ // PARA USUÁRIO
  "email": "leonnardomelo3@gmail.com",
  "password": "123",
  "nivelUsuario": 1, // Ou 2 para empresa
  "nickname": "Leonardo",
  "nomeReal": "Leonado Daitx",
  "dataNasc": "2005-09-07"
}

{ // PARA EMPRESA
  "email": "test2e2@example.com",
  "password": "123",
  "nome": "Nome da Empresa",
  "endereco": "Endereço da Empresa",
  "cidade": "Cidade da Empresa",
  "enderecoMaps": "Link do Mapa",
  "precoMedio": 0,
  "totalSemanal": 0,
  "imagemBanner": "url_da_imagem_banner",
  "imagemAvatar": "url_da_imagem_avatar",
  "horarioFuncionamento": "09:00 - 18:00",
  "abertoFechado": 1, // 1 = ABERTO, 0 = FECHADO
  "nivelUsuario": 2, // 2 = EMPRESA
  "nivelEmpresa": 1,
  "CNPJ": 17 // CNPJ DEVE SER UNICO
}

POST http://localhost:3000/api/autenticacao/recovery // RECUPERAR SENHA
{
  "email": "email@gmail.com",
  "codigo": null,
  "novaSenha": null
  // SE TIVER TUDO NULL, VAI ENVIAR O CODIGO. DAI TEM QUE COLOCAR O CODIGO DO EMAIL E A SENHA
}

POST http://localhost:3000/api/autenticacao/login // LOGIN USUÁRIO
{
  "email": "pedrohenriqueribeiro669@gmail.com",
  "password": "123",
  "codigoVerificacao": null // SE FOR NULL VAI ENVIAR O CODIGO, DAI SE FOR CORRETO VAI RETORNAR O TOKEN
}

// == BUSINESS MANAGEMENT == - AUTENTICADO

PUT http://localhost:3000/api/businessManagement/update-empresa
{ // DEVE ESTAR AUTENTICADO E DEVE TER O TOKEN, PARA PEGAR O ID VIA TOKEN
  "nome": "Nome Atualizado da Empresa",
  "endereco": "Novo Endereço da Empresa",
  "cidade": "Nova Cidade",
  "enderecoMaps": "https://link-do-mapa.com",
  "precoMedio": 150,
  "totalSemanal": 0, // PADRÃO É 0
  "imagemBanner": "https://link-da-imagem-banner.com/banner.jpg",
  "imagemAvatar": "https://link-da-imagem-avatar.com/avatar.jpg",
  "horarioFuncionamento": "08:00 - 20:00",
  "abertoFechado": 1, // BOOLEANO, 1 = ABERTO
  "nivelEmpresa": 1,
  "CNPJ": "00.000.000/0001-00"
}

POST http://localhost:3000/api/businessManagement/campo
{ // DEVE ESTAR AUTENTICADO E DEVE TER O TOKEN, PARA PEGAR O ID VIA TOKEN
  "nomeCampo": "Campo de Futebol",
  "bannerCampo": "https://example.com/banner.jpg",
  "preco": 100,
  "disponibilidade": 1,
  "horarios": {
    "segunda": ["15:00", "16:00", "17:00"],
    "terca": ["15:00", "16:00", "17:00"],
    "quarta": ["15:00", "16:00", "17:00"],
    "quinta": ["15:00", "16:00", "17:00"],
    "sexta": ["15:00", "16:00", "17:00"]
  }
}

// == FIELD SCHEDULE == - AUTENTICADO

POST http://localhost:3000/api/schedule/agendar
{ // DEVE ESTAR AUTENTICADO E DEVE TER O TOKEN, PARA PEGAR O ID VIA TOKEN
  "idCampo": 1,
  "idEmpresa": 1,
  "horario": {
    "segunda": ["15:00"]
  },
  "quantidadePessoas": 5,
  "semana": "2023-10-30"
}

// == ACCOUNT MANAGEMENT == - AUTENTICADO

GET http://localhost:3000/api/accountmanagement/profile
{
  // DEVE ESTAR COM O TOKEN NO HEADER PARA PUXAR
}

// == PAGINA HOME == - AUTENTICADO

GET http://localhost:3000/api/home/empresas
{

}

GET http://localhost:3000/api/home/campos/1
{ // O NÚMERO 1 É O ID DA EMPRESA

}